# Data Structures, Functions, Numpy & Pandas

### Section A: Data Structures & Control Structures

#### 1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [49]:
a=[1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [50]:
#append
a.append(9)
a

[1, 2, 3, 4, 5, 9]

In [51]:
a.append([10,56,67])
print(a)

[1, 2, 3, 4, 5, 9, [10, 56, 67]]


In [52]:
#Extend
a.extend([29,39])
a

[1, 2, 3, 4, 5, 9, [10, 56, 67], 29, 39]

In [53]:
#to insert a value at a particular index position
a.insert(2,1000)
a

[1, 2, 1000, 3, 4, 5, 9, [10, 56, 67], 29, 39]

In [54]:
a.remove(39) #removes a value from list
a

[1, 2, 1000, 3, 4, 5, 9, [10, 56, 67], 29]

In [55]:
a.pop() #pop is list in first out operation .it deletes last element  or specified index 
a

[1, 2, 1000, 3, 4, 5, 9, [10, 56, 67]]

In [56]:
a.clear()   #Empties the list
a

[]

In [57]:
a=[10,20,30,40,50,40,40]
a.index(20) #gives index of an element 

1

In [58]:
a.count(40)  # gives count of a specified number

3

In [59]:
a.sort() #used to sort values in order
a

[10, 20, 30, 40, 40, 40, 50]

In [60]:
a.reverse() #reverses the order of elements in list
a

[50, 40, 40, 40, 30, 20, 10]

#### 2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [61]:
tuple1=("BHANU","POOJITH","RAJ")
tuple1

('BHANU', 'POOJITH', 'RAJ')

In [62]:
tuple1[1]="PORUS"    #Can't chage tuple values 

TypeError: 'tuple' object does not support item assignment

In [63]:
# TypeError: 'tuple' object does not support item assignment
#Tuples are immutable, i.e., tuple items cannot be changes once created 


#### 3. Create a set of integers with some duplicate values. Print the set and explain the output.

In [64]:
set_values={1,2,2,3,4,5,6,6}
print(type(set_values))            
set_values                       #sets don't allow duplicate values, any duplicate values entered will be removed automatically

<class 'set'>


{1, 2, 3, 4, 5, 6}

#### 4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [65]:
student= {
    "name": "Prabhas",
    "age": 23,
    "city": "Banglore"
}

student["age"] = 30
student["email"] = "Prabhas1234@gmail.com"

print("Final Dictionary:", student)



Final Dictionary: {'name': 'Prabhas', 'age': 30, 'city': 'Banglore', 'email': 'Prabhas1234@gmail.com'}


#### 5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [66]:
age=23
if age>=18:
    print("Eligible to Vote")
else:
    print(("Not Eligible to Vote"))

Eligible to Vote


#### 6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [67]:
marks = 92

if marks >= 90:
    print("Grade: A")
elif marks >= 75:
    print("Grade: B")
elif marks >= 50:
    print("Grade: C")
else:
    print("Fail")

Grade: A


#### 7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.


In [68]:
num = 39

if num > 0:
    print("Positive Number")
    if num % 2 == 0:
        print("Even Number")
    else:
        print("Odd Number")
elif num == 0:
    print("Zero")
else:
    print("Negative Number")

Positive Number
Odd Number


# Section B: Numpy

#### 8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10


In [69]:
import numpy as np
import pandas as pd

In [70]:
scalar = np.array(5)
print("Scalar:",scalar)

array1 = np.array([1, 2, 3, 4, 5])
print("\n1D Array:")
print(array1)

array2 = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("\n2D Array:")
print(array2)

#array3=np.arange(10,70,10).reshape(2,3)    #this can also be used 
#print(array3)


Scalar: 5

1D Array:
[1 2 3 4 5]

2D Array:
[[10 20 30]
 [40 50 60]]


#### 9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [71]:
arr= np.random.randint(0, 101, size=(4, 4))
print(arr)

[[100  31  89   2]
 [  2  77  51  14]
 [ 84  15  38  59]
 [ 70  95  75  72]]


#### 10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [72]:
array=np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

df = pd.DataFrame(array, columns=["A", "B", "C"])

df

,A,B,C
0,1,2,3
1,4,5,6
2,7,8,9


# Section C: Exploring Pandas

#### 11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows


In [73]:
data = {
    "Name": ["Ram", "Akhil", "Mahesh", "Midhun", "Teja",
             "Dileep", "Madhan", "Raj", "Tej", "Bhanu"],
    "Age": [23, 25, 22, 24, 26,
            28, 27, 24, 29, 25],
    "City": ["Delhi", "Mumbai", "Chennai", "Delhi", "Pune",
             "Hyderabad", "Kolkata", "Mumbai", "Delhi", "Mumbai"],
    "Salary": [50000, 60000, np.nan, 55000, 65000,
               70000, np.nan, 62000, 72000, 60000]
}

df = pd.DataFrame(data)
df


,Name,Age,City,Salary
0,Ram,23,Delhi,50000.0
1,Akhil,25,Mumbai,60000.0
2,Mahesh,22,Chennai,NaN
3,Midhun,24,Delhi,55000.0
4,Teja,26,Pune,65000.0
5,Dileep,28,Hyderabad,70000.0
6,Madhan,27,Kolkata,NaN
7,Raj,24,Mumbai,62000.0
8,Tej,29,Delhi,72000.0
9,Bhanu,25,Mumbai,60000.0


In [74]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Name    10 non-null     object 
 1   Age     10 non-null     int64  
 2   City    10 non-null     object 
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 452.0+ bytes


In [75]:
df.describe()

,Age,Salary
count,10.000000,8.000000
mean,25.300000,61750.000000
std,2.213594,7304.597378
min,22.000000,50000.000000
25%,24.000000,58750.000000
50%,25.000000,61000.000000
75%,26.750000,66250.000000
max,29.000000,72000.000000


In [76]:
df[["Name", "City"]]

,Name,City
0,Ram,Delhi
1,Akhil,Mumbai
2,Mahesh,Chennai
3,Midhun,Delhi
4,Teja,Pune
5,Dileep,Hyderabad
6,Madhan,Kolkata
7,Raj,Mumbai
8,Tej,Delhi
9,Bhanu,Mumbai


In [77]:
df_drop = df.drop(columns=["City"])
df_drop

,Name,Age,Salary
0,Ram,23,50000.0
1,Akhil,25,60000.0
2,Mahesh,22,NaN
3,Midhun,24,55000.0
4,Teja,26,65000.0
5,Dileep,28,70000.0
6,Madhan,27,NaN
7,Raj,24,62000.0
8,Tej,29,72000.0
9,Bhanu,25,60000.0


In [78]:
df["Salary"] = df["Salary"].fillna(df["Salary"].mean())
df

,Name,Age,City,Salary
0,Ram,23,Delhi,50000.0
1,Akhil,25,Mumbai,60000.0
2,Mahesh,22,Chennai,61750.0
3,Midhun,24,Delhi,55000.0
4,Teja,26,Pune,65000.0
5,Dileep,28,Hyderabad,70000.0
6,Madhan,27,Kolkata,61750.0
7,Raj,24,Mumbai,62000.0
8,Tej,29,Delhi,72000.0
9,Bhanu,25,Mumbai,60000.0


In [79]:
df_no_duplicates = df.drop_duplicates()
df_no_duplicates

,Name,Age,City,Salary
0,Ram,23,Delhi,50000.0
1,Akhil,25,Mumbai,60000.0
2,Mahesh,22,Chennai,61750.0
3,Midhun,24,Delhi,55000.0
4,Teja,26,Pune,65000.0
5,Dileep,28,Hyderabad,70000.0
6,Madhan,27,Kolkata,61750.0
7,Raj,24,Mumbai,62000.0
8,Tej,29,Delhi,72000.0
9,Bhanu,25,Mumbai,60000.0
